In [13]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [14]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

train_target = train.Survived
train.drop('Survived',1,inplace=True)

# 第一步 观察、分析数据

In [15]:
# 统计非空行，发现缺失值
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
PassengerId    891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(4), object(5)
memory usage: 76.6+ KB

训练集有12个列，891行

数值：
PassangerId、Survived、Pclass、Age、SibSp、Parch、Fare 

字符串：
Name 、Sex 、Ticket 、Cabin 、Embarked 



存在缺失值的列：
Age 714 个有效值，缺失177,经查阅资料，尝试用中值年龄替换空值，对于异常值，这样比平均值鲁棒性更强

Cabin 204 个值，缺失687

Embarked 889个值，缺失2

In [16]:
train['Age'].fillna(train['Age'].median(), inplace=True)
train.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean    446.000000    2.308642   29.361582    0.523008    0.381594   32.204208
std     257.353842    0.836071   13.019697    1.102743    0.806057   49.693429
min       1.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%     223.500000    2.000000   22.000000    0.000000    0.000000    7.910400
50%     446.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%     668.500000    3.000000   35.000000    1.000000    0.000000   31.000000
max     891.000000    3.000000   80.000000    8.000000    6.000000  512.329200

# 第二步 特征工程

In [17]:
total = train.append(test)

In [22]:
def get_titles():
    # 从名字中提取唯一有用的信息：头衔
    total['Title'] = total['Name'].map(lambda name:name.split(',')[1].split('.')[0].strip())
    
    # 将多个头衔映射到较少的身份
    Title_Dictionary = {
                        "Capt":       "Officer",
                        "Col":        "Officer",
                        "Major":      "Officer",
                        "Jonkheer":   "Nobles",
                        "Don":        "Nobles",
                        "Sir" :       "Nobles",
                        "Dr":         "Officer",
                        "Rev":        "Officer",
                        "the Countess":"Nobles",
                        "Dona":       "Nobles",
                        "Mme":        "Mrs",
                        "Mlle":       "Miss",
                        "Ms":         "Mrs",
                        "Mr" :        "Mr",
                        "Mrs" :       "Mrs",
                        "Miss" :      "Miss",
                        "Master" :    "Master",
                        "Lady" :      "Nobles"
                        }
    
    total['Title'] = total.Title.map(Title_Dictionary)

In [26]:
get_titles()
total

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr
5,6,3,"Moran, Mr. James",male,28.0,0,0,330877,8.4583,NaN,Q,Mr
6,7,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Mr
7,8,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,Master
8,9,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,Mrs
9,10,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,Mrs
10,11,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,Miss
11,12,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,Miss
12,13,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S,Mr
13,14,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S,Mr
14,15,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S,Miss
15,16,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,Mrs
16,17,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q,Master
17,18,2,"Williams, Mr. Charles Eugene",male,28.0,0,0,244373,13.0000,NaN,S,Mr
18,19,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S,Mrs
19,20,3,"Masselmani, Mrs. Fatima",female,28.0,0,0,2649,7.2250,NaN,C,Mrs
20,21,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S,Mr
21,22,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S,Mr
22,23,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q,Miss
23,24,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S,Mr
24,25,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S,Miss
25,26,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S,Mrs
26,27,3,"Emir, Mr. Farred Chehab",male,28.0,0,0,2631,7.2250,NaN,C,Mr
27,28,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,Mr
28,29,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,28.0,0,0,330959,7.8792,NaN,Q,Miss
29,30,3,"Todoroff, Mr. Lalio",male,28.0,0,0,349216,7.8958,NaN,S,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...
388,1280,3,"Canavan, Mr. Patrick",male,21.0,0,0,364858,7.7500,NaN,Q,Mr
389,1281,3,"Palsson, Master. Paul Folke",male,6.0,3,1,349909,21.0750,NaN,S,Master
390,1282,1,"Payne, Mr. Vivian Ponsonby",male,23.0,0,0,12749,93.5000,B24,S,Mr
391,1283,1,"Lines, Mrs. Ernest H (Elizabeth Lindsey James)",female,51.0,0,1,PC 17592,39.4000,D28,S,Mrs
392,1284,3,"Abbott, Master. Eugene Joseph",male,13.0,0,2,C.A. 2673,20.2500,NaN,S,Master
393,1285,2,"Gilbert, Mr. William",male,47.0,0,0,C.A. 30769,10.5000,NaN,S,Mr
394,1286,3,"Kink-Heilmann, Mr. Anton",male,29.0,3,1,315153,22.0250,NaN,S,Mr
395,1287,1,"Smith, Mrs. Lucien Philip (Mary Eloise Hughes)",female,18.0,1,0,13695,60.0000,C31,S,Mrs
396,1288,3,"Colbert, Mr. Patrick",male,24.0,0,0,371109,7.2500,NaN,Q,Mr
397,1289,1,"Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...",female,48.0,1,1,13567,79.2000,B41,C,Mrs
398,1290,3,"Larsson-Rondberg, Mr. Edvard A",male,22.0,0,0,347065,7.7750,NaN,S,Mr
399,1291,3,"Conlon, Mr. Thomas Henry",male,31.0,0,0,21332,7.7333,NaN,Q,Mr
400,1292,1,"Bonnell, Miss. Caroline",female,30.0,0,0,36928,164.8667,C7,S,Miss
401,1293,2,"Gale, Mr. Harry",male,38.0,1,0,28664,21.0000,NaN,S,Mr
402,1294,1,"Gibson, Miss. Dorothy Winifred",female,22.0,0,1,112378,59.4000,NaN,C,Miss
403,1295,1,"Carrau, Mr. Jose Pedro",male,17.0,0,0,113059,47.1000,NaN,S,Mr
404,1296,1,"Frauenthal, Mr. Isaac Gerald",male,43.0,1,0,17765,27.7208,D40,C,Mr
405,1297,2,"Nourney, Mr. Alfred (Baron von Drachstedt"")""",male,20.0,0,0,SC/PARIS 2166,13.8625,D38,C,Mr
406,1298,2,"Ware, Mr. William Jeffery",male,23.0,1,0,28666,10.5000,NaN,S,Mr
407,1299,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C,Mr
408,1300,3,"Riordan, Miss. Johanna Hannah""""",female,NaN,0,0,334915,7.7208,NaN,Q,Miss
409,1301,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S,Miss
410,1302,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q,Miss
411,1303,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q,Mrs
412,1304,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S,Miss
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,Mr
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,Nobles
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,Mr
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,Mr
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,Master

用平均值或中位年龄代替年龄的缺失值，可能不是最佳解决方案，因为年龄可能因团体和乘客类别而异。

尝试按性别，标题和乘客类分组。

In [28]:
grouped_train = total.head(891).groupby(['Sex','Pclass','Title'])
grouped_median_train = grouped_train.median()
grouped_test = total.iloc[891:].groupby(['Sex','Pclass','Title'])
grouped_median_test = grouped_test.median()

In [29]:
grouped_median_train

                       PassengerId   Age  SibSp  Parch       Fare
Sex    Pclass Title
female 1      Miss           369.0  29.5    0.0    0.0   88.25000
              Mrs            499.0  38.0    1.0    0.0   79.20000
              Nobles         658.5  40.5    0.5    0.0   63.05000
              Officer        797.0  49.0    0.0    0.0   25.92920
       2      Miss           437.5  24.0    0.0    0.0   13.00000
              Mrs            439.5  31.5    1.0    0.0   26.00000
       3      Miss           372.0  22.0    0.0    0.0    8.75625
              Mrs            405.5  29.0    1.0    1.0   15.97500
male   1      Master         446.0   4.0    1.0    2.0  120.00000
              Mr             463.0  36.0    0.0    0.0   42.40000
              Nobles         600.0  40.0    0.0    0.0   27.72080
              Officer        648.0  50.0    0.0    0.0   35.50000
       2      Master         408.0   1.0    1.0    1.0   26.00000
              Mr             440.0  30.0    0.0    0.0   13.00000
              Officer        358.5  46.5    0.0    0.0   13.00000
       3      Master         270.5   6.5    3.5    1.0   28.51250
              Mr             472.0  28.0    0.0    0.0    7.89580

In [32]:
def process_age():
    
    global total
    
    # a function that fills the missing values of the Age variable
    
    def fillAges(row):
        if row['Sex']=='female' and row['Pclass'] == 1:
            if row['Title'] == 'Miss':
                return 30
            elif row['Title'] == 'Mrs':
                return 45
            elif row['Title'] == 'Officer':
                return 49
            elif row['Title'] == 'Royalty':
                return 39
        elif row['Sex']=='female' and row['Pclass'] == 2:
            if row['Title'] == 'Miss':
                return 20
            elif row['Title'] == 'Mrs':
                return 30
        elif row['Sex']=='female' and row['Pclass'] == 3:
            if row['Title'] == 'Miss':
                return 18
            elif row['Title'] == 'Mrs':
                return 31
        elif row['Sex']=='male' and row['Pclass'] == 1:
            if row['Title'] == 'Master':
                return 6
            elif row['Title'] == 'Mr':
                return 41.5
            elif row['Title'] == 'Officer':
                return 52
            elif row['Title'] == 'Royalty':
                return 40
        elif row['Sex']=='male' and row['Pclass'] == 2:
            if row['Title'] == 'Master':
                return 2
            elif row['Title'] == 'Mr':
                return 30
            elif row['Title'] == 'Officer':
                return 41.5
        elif row['Sex']=='male' and row['Pclass'] == 3:
            if row['Title'] == 'Master':
                return 6
            elif row['Title'] == 'Mr':
                return 26
    
    total.Age = total.apply(lambda r : fillAges(r) if np.isnan(r['Age']) else r['Age'], axis=1)

In [34]:
process_age()

In [37]:
def process_names():
    
    global total
    # 删去name
    total.drop('Name',axis=1,inplace=True)
    
    # 将分类变量title转换为“哑变量矩阵”或“指标矩阵”。
    titles_dummies = pd.get_dummies(total['Title'],prefix='Title')
    total = pd.concat([total,titles_dummies],axis=1)
    
    # 删去title
    total.drop('Title',axis=1,inplace=True)

In [ ]:
process_names()

In [39]:
total

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Nobles,Title_Officer
0,1,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,0,1,0,0,0
1,2,1,female,38.0,1,0,PC 17599,71.2833,C85,C,0,0,0,1,0,0
2,3,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,1,0,0,0,0
3,4,1,female,35.0,1,0,113803,53.1000,C123,S,0,0,0,1,0,0
4,5,3,male,35.0,0,0,373450,8.0500,NaN,S,0,0,1,0,0,0
5,6,3,male,28.0,0,0,330877,8.4583,NaN,Q,0,0,1,0,0,0
6,7,1,male,54.0,0,0,17463,51.8625,E46,S,0,0,1,0,0,0
7,8,3,male,2.0,3,1,349909,21.0750,NaN,S,1,0,0,0,0,0
8,9,3,female,27.0,0,2,347742,11.1333,NaN,S,0,0,0,1,0,0
9,10,2,female,14.0,1,0,237736,30.0708,NaN,C,0,0,0,1,0,0
10,11,3,female,4.0,1,1,PP 9549,16.7000,G6,S,0,1,0,0,0,0
11,12,1,female,58.0,0,0,113783,26.5500,C103,S,0,1,0,0,0,0
12,13,3,male,20.0,0,0,A/5. 2151,8.0500,NaN,S,0,0,1,0,0,0
13,14,3,male,39.0,1,5,347082,31.2750,NaN,S,0,0,1,0,0,0
14,15,3,female,14.0,0,0,350406,7.8542,NaN,S,0,1,0,0,0,0
15,16,2,female,55.0,0,0,248706,16.0000,NaN,S,0,0,0,1,0,0
16,17,3,male,2.0,4,1,382652,29.1250,NaN,Q,1,0,0,0,0,0
17,18,2,male,28.0,0,0,244373,13.0000,NaN,S,0,0,1,0,0,0
18,19,3,female,31.0,1,0,345763,18.0000,NaN,S,0,0,0,1,0,0
19,20,3,female,28.0,0,0,2649,7.2250,NaN,C,0,0,0,1,0,0
20,21,2,male,35.0,0,0,239865,26.0000,NaN,S,0,0,1,0,0,0
21,22,2,male,34.0,0,0,248698,13.0000,D56,S,0,0,1,0,0,0
22,23,3,female,15.0,0,0,330923,8.0292,NaN,Q,0,1,0,0,0,0
23,24,1,male,28.0,0,0,113788,35.5000,A6,S,0,0,1,0,0,0
24,25,3,female,8.0,3,1,349909,21.0750,NaN,S,0,1,0,0,0,0
25,26,3,female,38.0,1,5,347077,31.3875,NaN,S,0,0,0,1,0,0
26,27,3,male,28.0,0,0,2631,7.2250,NaN,C,0,0,1,0,0,0
27,28,1,male,19.0,3,2,19950,263.0000,C23 C25 C27,S,0,0,1,0,0,0
28,29,3,female,28.0,0,0,330959,7.8792,NaN,Q,0,1,0,0,0,0
29,30,3,male,28.0,0,0,349216,7.8958,NaN,S,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,1280,3,male,21.0,0,0,364858,7.7500,NaN,Q,0,0,1,0,0,0
389,1281,3,male,6.0,3,1,349909,21.0750,NaN,S,1,0,0,0,0,0
390,1282,1,male,23.0,0,0,12749,93.5000,B24,S,0,0,1,0,0,0
391,1283,1,female,51.0,0,1,PC 17592,39.4000,D28,S,0,0,0,1,0,0
392,1284,3,male,13.0,0,2,C.A. 2673,20.2500,NaN,S,1,0,0,0,0,0
393,1285,2,male,47.0,0,0,C.A. 30769,10.5000,NaN,S,0,0,1,0,0,0
394,1286,3,male,29.0,3,1,315153,22.0250,NaN,S,0,0,1,0,0,0
395,1287,1,female,18.0,1,0,13695,60.0000,C31,S,0,0,0,1,0,0
396,1288,3,male,24.0,0,0,371109,7.2500,NaN,Q,0,0,1,0,0,0
397,1289,1,female,48.0,1,1,13567,79.2000,B41,C,0,0,0,1,0,0
398,1290,3,male,22.0,0,0,347065,7.7750,NaN,S,0,0,1,0,0,0
399,1291,3,male,31.0,0,0,21332,7.7333,NaN,Q,0,0,1,0,0,0
400,1292,1,female,30.0,0,0,36928,164.8667,C7,S,0,1,0,0,0,0
401,1293,2,male,38.0,1,0,28664,21.0000,NaN,S,0,0,1,0,0,0
402,1294,1,female,22.0,0,1,112378,59.4000,NaN,C,0,1,0,0,0,0
403,1295,1,male,17.0,0,0,113059,47.1000,NaN,S,0,0,1,0,0,0
404,1296,1,male,43.0,1,0,17765,27.7208,D40,C,0,0,1,0,0,0
405,1297,2,male,20.0,0,0,SC/PARIS 2166,13.8625,D38,C,0,0,1,0,0,0
406,1298,2,male,23.0,1,0,28666,10.5000,NaN,S,0,0,1,0,0,0
407,1299,1,male,50.0,1,1,113503,211.5000,C80,C,0,0,1,0,0,0
408,1300,3,female,18.0,0,0,334915,7.7208,NaN,Q,0,1,0,0,0,0
409,1301,3,female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S,0,1,0,0,0,0
410,1302,3,female,18.0,0,0,365237,7.7500,NaN,Q,0,1,0,0,0,0
411,1303,1,female,37.0,1,0,19928,90.0000,C78,Q,0,0,0,1,0,0
412,1304,3,female,28.0,0,0,347086,7.7750,NaN,S,0,1,0,0,0,0
413,1305,3,male,26.0,0,0,A.5. 3236,8.0500,NaN,S,0,0,1,0,0,0
414,1306,1,female,39.0,0,0,PC 17758,108.9000,C105,C,0,0,0,0,1,0
415,1307,3,male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,0,0,1,0,0,0
416,1308,3,male,26.0,0,0,359309,8.0500,NaN,S,0,0,1,0,0,0
417,1309,3,male,6.0,1,1,2668,22.3583,NaN,C,1,0,0,0,0,0

处理登船港口编号

In [44]:
#因为只有一个缺失值，船票价使用平均值填充
total.Fare.fillna(total.Fare.mean(),inplace=True)

In [45]:
# 登船港口编号只有两个缺失，使用最频繁的S填入
total.Embarked.fillna('S',inplace=True)    
# 转化为哑变量
embarked_dummies = pd.get_dummies(total['Embarked'],prefix='Embarked')
total = pd.concat([total,embarked_dummies],axis=1)
total.drop('Embarked',axis=1,inplace=True)

处理客舱位置

In [47]:
# 用U代替NA
total.Cabin.fillna('U',inplace=True)
    
# 用首字母映射舱位
total['Cabin'] = total['Cabin'].map(lambda c : c[0])
    
# 转化为哑变量
cabin_dummies = pd.get_dummies(total['Cabin'],prefix='Cabin')
    
total = pd.concat([total,cabin_dummies],axis=1)
    
total.drop('Cabin',axis=1,inplace=True)

处理乘客性别：映射到1与0

In [49]:
total['Sex'] = total['Sex'].map({'male':1,'female':0})

处理客舱等级

In [50]:
pclass_dummies = pd.get_dummies(total['Pclass'],prefix="Pclass")
# adding dummy variables
total = pd.concat([total,pclass_dummies],axis=1)
    
# removing "Pclass"
    
total.drop('Pclass',axis=1,inplace=True)

In [51]:
total

,PassengerId,Sex,Age,SibSp,Parch,Ticket,Fare,Title_Master,Title_Miss,Title_Mr,...,Cabin_C,Cabin_D,Cabin_E,Cabin_F,Cabin_G,Cabin_T,Cabin_U,Pclass_1,Pclass_2,Pclass_3
0,1,1,22.0,1,0,A/5 21171,7.2500,0,0,1,...,0,0,0,0,0,0,1,0,0,1
1,2,0,38.0,1,0,PC 17599,71.2833,0,0,0,...,1,0,0,0,0,0,0,1,0,0
2,3,0,26.0,0,0,STON/O2. 3101282,7.9250,0,1,0,...,0,0,0,0,0,0,1,0,0,1
3,4,0,35.0,1,0,113803,53.1000,0,0,0,...,1,0,0,0,0,0,0,1,0,0
4,5,1,35.0,0,0,373450,8.0500,0,0,1,...,0,0,0,0,0,0,1,0,0,1
5,6,1,28.0,0,0,330877,8.4583,0,0,1,...,0,0,0,0,0,0,1,0,0,1
6,7,1,54.0,0,0,17463,51.8625,0,0,1,...,0,0,1,0,0,0,0,1,0,0
7,8,1,2.0,3,1,349909,21.0750,1,0,0,...,0,0,0,0,0,0,1,0,0,1
8,9,0,27.0,0,2,347742,11.1333,0,0,0,...,0,0,0,0,0,0,1,0,0,1
9,10,0,14.0,1,0,237736,30.0708,0,0,0,...,0,0,0,0,0,0,1,0,1,0
10,11,0,4.0,1,1,PP 9549,16.7000,0,1,0,...,0,0,0,0,1,0,0,0,0,1
11,12,0,58.0,0,0,113783,26.5500,0,1,0,...,1,0,0,0,0,0,0,1,0,0
12,13,1,20.0,0,0,A/5. 2151,8.0500,0,0,1,...,0,0,0,0,0,0,1,0,0,1
13,14,1,39.0,1,5,347082,31.2750,0,0,1,...,0,0,0,0,0,0,1,0,0,1
14,15,0,14.0,0,0,350406,7.8542,0,1,0,...,0,0,0,0,0,0,1,0,0,1
15,16,0,55.0,0,0,248706,16.0000,0,0,0,...,0,0,0,0,0,0,1,0,1,0
16,17,1,2.0,4,1,382652,29.1250,1,0,0,...,0,0,0,0,0,0,1,0,0,1
17,18,1,28.0,0,0,244373,13.0000,0,0,1,...,0,0,0,0,0,0,1,0,1,0
18,19,0,31.0,1,0,345763,18.0000,0,0,0,...,0,0,0,0,0,0,1,0,0,1
19,20,0,28.0,0,0,2649,7.2250,0,0,0,...,0,0,0,0,0,0,1,0,0,1
20,21,1,35.0,0,0,239865,26.0000,0,0,1,...,0,0,0,0,0,0,1,0,1,0
21,22,1,34.0,0,0,248698,13.0000,0,0,1,...,0,1,0,0,0,0,0,0,1,0
22,23,0,15.0,0,0,330923,8.0292,0,1,0,...,0,0,0,0,0,0,1,0,0,1
23,24,1,28.0,0,0,113788,35.5000,0,0,1,...,0,0,0,0,0,0,0,1,0,0
24,25,0,8.0,3,1,349909,21.0750,0,1,0,...,0,0,0,0,0,0,1,0,0,1
25,26,0,38.0,1,5,347077,31.3875,0,0,0,...,0,0,0,0,0,0,1,0,0,1
26,27,1,28.0,0,0,2631,7.2250,0,0,1,...,0,0,0,0,0,0,1,0,0,1
27,28,1,19.0,3,2,19950,263.0000,0,0,1,...,1,0,0,0,0,0,0,1,0,0
28,29,0,28.0,0,0,330959,7.8792,0,1,0,...,0,0,0,0,0,0,1,0,0,1
29,30,1,28.0,0,0,349216,7.8958,0,0,1,...,0,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,1280,1,21.0,0,0,364858,7.7500,0,0,1,...,0,0,0,0,0,0,1,0,0,1
389,1281,1,6.0,3,1,349909,21.0750,1,0,0,...,0,0,0,0,0,0,1,0,0,1
390,1282,1,23.0,0,0,12749,93.5000,0,0,1,...,0,0,0,0,0,0,0,1,0,0
391,1283,0,51.0,0,1,PC 17592,39.4000,0,0,0,...,0,1,0,0,0,0,0,1,0,0
392,1284,1,13.0,0,2,C.A. 2673,20.2500,1,0,0,...,0,0,0,0,0,0,1,0,0,1
393,1285,1,47.0,0,0,C.A. 30769,10.5000,0,0,1,...,0,0,0,0,0,0,1,0,1,0
394,1286,1,29.0,3,1,315153,22.0250,0,0,1,...,0,0,0,0,0,0,1,0,0,1
395,1287,0,18.0,1,0,13695,60.0000,0,0,0,...,1,0,0,0,0,0,0,1,0,0
396,1288,1,24.0,0,0,371109,7.2500,0,0,1,...,0,0,0,0,0,0,1,0,0,1
397,1289,0,48.0,1,1,13567,79.2000,0,0,0,...,0,0,0,0,0,0,0,1,0,0
398,1290,1,22.0,0,0,347065,7.7750,0,0,1,...,0,0,0,0,0,0,1,0,0,1
399,1291,1,31.0,0,0,21332,7.7333,0,0,1,...,0,0,0,0,0,0,1,0,0,1
400,1292,0,30.0,0,0,36928,164.8667,0,1,0,...,1,0,0,0,0,0,0,1,0,0
401,1293,1,38.0,1,0,28664,21.0000,0,0,1,...,0,0,0,0,0,0,1,0,1,0
402,1294,0,22.0,0,1,112378,59.4000,0,1,0,...,0,0,0,0,0,0,1,1,0,0
403,1295,1,17.0,0,0,113059,47.1000,0,0,1,...,0,0,0,0,0,0,1,1,0,0
404,1296,1,43.0,1,0,17765,27.7208,0,0,1,...,0,1,0,0,0,0,0,1,0,0
405,1297,1,20.0,0,0,SC/PARIS 2166,13.8625,0,0,1,...,0,1,0,0,0,0,0,0,1,0
406,1298,1,23.0,1,0,28666,10.5000,0,0,1,...,0,0,0,0,0,0,1,0,1,0
407,1299,1,50.0,1,1,113503,211.5000,0,0,1,...,1,0,0,0,0,0,0,1,0,0
408,1300,0,18.0,0,0,334915,7.7208,0,1,0,...,0,0,0,0,0,0,1,0,0,1
409,1301,0,3.0,1,1,SOTON/O.Q. 3101315,13.7750,0,1,0,...,0,0,0,0,0,0,1,0,0,1
410,1302,0,18.0,0,0,365237,7.7500,0,1,0,...,0,0,0,0,0,0,1,0,0,1
411,1303,0,37.0,1,0,19928,90.0000,0,0,0,...,1,0,0,0,0,0,0,1,0,0
412,1304,0,28.0,0,0,347086,7.7750,0,1,0,...,0,0,0,0,0,0,1,0,0,1
413,1305,1,26.0,0,0,A.5. 3236,8.0500,0,0,1,...,0,0,0,0,0,0,1,0,0,1
414,1306,0,39.0,0,0,PC 17758,108.9000,0,0,0,...,1,0,0,0,0,0,0,1,0,0
415,1307,1,38.5,0,0,SOTON/O.Q. 3101262,7.2500,0,0,1,...,0,0,0,0,0,0,1,0,0,1
416,1308,1,26.0,0,0,359309,8.0500,0,0,1,...,0,0,0,0,0,0,1,0,0,1
417,1309,1,6.0,1,1,2668,22.3583,1,0,0,...,0,0,0,0,0,0,1,0,0,1

处理船票号：

通过提取票号前缀来预处理船票。 当提取前缀失败时返回XXX。

然后使用虚拟编码对前缀进行编码。

# a function that extracts each prefix of the ticket, returns 'XXX' if no prefix (i.e the ticket is a digit)
def cleanTicket(ticket):
    ticket = ticket.replace('.','')
    ticket = ticket.replace('/','')
    ticket = ticket.split()
    ticket = map(lambda t : t.strip() , ticket)
    ticket = list( filter(lambda t : not t.isdigit(), ticket) )
    if len(ticket) > 0:
        return ticket[0]
    else: 
        return 'UNKNOWN'

In [62]:
total['Ticket'] = total['Ticket'].map(cleanTicket)
tickets_dummies = pd.get_dummies(total['Ticket'],prefix='Ticket')
total = pd.concat([total, tickets_dummies],axis=1)
total.drop('Ticket',inplace=True,axis=1)

KeyError: 'Ticket'

In [ ]:
total

处理家庭等信息

SibSp 兄弟姐妹和配偶在船数量

ParCh 父母孩子在船数量

In [63]:
# introducing a new feature : the size of families (including the passenger)
total['FamilySize'] = total['Parch'] + total['SibSp'] + 1
    
# introducing other features based on the family size
total['Singleton'] = total['FamilySize'].map(lambda s : 1 if s == 1 else 0)
total['SmallFamily'] = total['FamilySize'].map(lambda s : 1 if 2<=s<=4 else 0)
total['LargeFamily'] = total['FamilySize'].map(lambda s : 1 if 5<=s else 0)

此过程产生了4个新特征：

FamilySize：包括乘客（他/她）在内的亲戚总数。

Sigleton： 一个布尔变量，描述size = 1家族

SmallFamily： 一个布尔变量，描述2 <= size <= 4家族

LargeFamily： 一个布尔变量，描述 5 < size 家族

In [64]:
total

,PassengerId,Sex,Age,SibSp,Parch,Fare,Title_Master,Title_Miss,Title_Mr,Title_Mrs,...,Ticket_STONO2,Ticket_STONOQ,Ticket_SWPP,Ticket_WC,Ticket_WEP,Ticket_XXX,FamilySize,Singleton,SmallFamily,LargeFamily
0,1,1,22.0,1,0,7.2500,0,0,1,0,...,0,0,0,0,0,0,2,0,1,0
1,2,0,38.0,1,0,71.2833,0,0,0,1,...,0,0,0,0,0,0,2,0,1,0
2,3,0,26.0,0,0,7.9250,0,1,0,0,...,1,0,0,0,0,0,1,1,0,0
3,4,0,35.0,1,0,53.1000,0,0,0,1,...,0,0,0,0,0,1,2,0,1,0
4,5,1,35.0,0,0,8.0500,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
5,6,1,28.0,0,0,8.4583,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
6,7,1,54.0,0,0,51.8625,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
7,8,1,2.0,3,1,21.0750,1,0,0,0,...,0,0,0,0,0,1,5,0,0,1
8,9,0,27.0,0,2,11.1333,0,0,0,1,...,0,0,0,0,0,1,3,0,1,0
9,10,0,14.0,1,0,30.0708,0,0,0,1,...,0,0,0,0,0,1,2,0,1,0
10,11,0,4.0,1,1,16.7000,0,1,0,0,...,0,0,0,0,0,0,3,0,1,0
11,12,0,58.0,0,0,26.5500,0,1,0,0,...,0,0,0,0,0,1,1,1,0,0
12,13,1,20.0,0,0,8.0500,0,0,1,0,...,0,0,0,0,0,0,1,1,0,0
13,14,1,39.0,1,5,31.2750,0,0,1,0,...,0,0,0,0,0,1,7,0,0,1
14,15,0,14.0,0,0,7.8542,0,1,0,0,...,0,0,0,0,0,1,1,1,0,0
15,16,0,55.0,0,0,16.0000,0,0,0,1,...,0,0,0,0,0,1,1,1,0,0
16,17,1,2.0,4,1,29.1250,1,0,0,0,...,0,0,0,0,0,1,6,0,0,1
17,18,1,28.0,0,0,13.0000,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
18,19,0,31.0,1,0,18.0000,0,0,0,1,...,0,0,0,0,0,1,2,0,1,0
19,20,0,28.0,0,0,7.2250,0,0,0,1,...,0,0,0,0,0,1,1,1,0,0
20,21,1,35.0,0,0,26.0000,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
21,22,1,34.0,0,0,13.0000,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
22,23,0,15.0,0,0,8.0292,0,1,0,0,...,0,0,0,0,0,1,1,1,0,0
23,24,1,28.0,0,0,35.5000,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
24,25,0,8.0,3,1,21.0750,0,1,0,0,...,0,0,0,0,0,1,5,0,0,1
25,26,0,38.0,1,5,31.3875,0,0,0,1,...,0,0,0,0,0,1,7,0,0,1
26,27,1,28.0,0,0,7.2250,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
27,28,1,19.0,3,2,263.0000,0,0,1,0,...,0,0,0,0,0,1,6,0,0,1
28,29,0,28.0,0,0,7.8792,0,1,0,0,...,0,0,0,0,0,1,1,1,0,0
29,30,1,28.0,0,0,7.8958,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,1280,1,21.0,0,0,7.7500,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
389,1281,1,6.0,3,1,21.0750,1,0,0,0,...,0,0,0,0,0,1,5,0,0,1
390,1282,1,23.0,0,0,93.5000,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
391,1283,0,51.0,0,1,39.4000,0,0,0,1,...,0,0,0,0,0,0,2,0,1,0
392,1284,1,13.0,0,2,20.2500,1,0,0,0,...,0,0,0,0,0,0,3,0,1,0
393,1285,1,47.0,0,0,10.5000,0,0,1,0,...,0,0,0,0,0,0,1,1,0,0
394,1286,1,29.0,3,1,22.0250,0,0,1,0,...,0,0,0,0,0,1,5,0,0,1
395,1287,0,18.0,1,0,60.0000,0,0,0,1,...,0,0,0,0,0,1,2,0,1,0
396,1288,1,24.0,0,0,7.2500,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
397,1289,0,48.0,1,1,79.2000,0,0,0,1,...,0,0,0,0,0,1,3,0,1,0
398,1290,1,22.0,0,0,7.7750,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
399,1291,1,31.0,0,0,7.7333,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
400,1292,0,30.0,0,0,164.8667,0,1,0,0,...,0,0,0,0,0,1,1,1,0,0
401,1293,1,38.0,1,0,21.0000,0,0,1,0,...,0,0,0,0,0,1,2,0,1,0
402,1294,0,22.0,0,1,59.4000,0,1,0,0,...,0,0,0,0,0,1,2,0,1,0
403,1295,1,17.0,0,0,47.1000,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
404,1296,1,43.0,1,0,27.7208,0,0,1,0,...,0,0,0,0,0,1,2,0,1,0
405,1297,1,20.0,0,0,13.8625,0,0,1,0,...,0,0,0,0,0,0,1,1,0,0
406,1298,1,23.0,1,0,10.5000,0,0,1,0,...,0,0,0,0,0,1,2,0,1,0
407,1299,1,50.0,1,1,211.5000,0,0,1,0,...,0,0,0,0,0,1,3,0,1,0
408,1300,0,18.0,0,0,7.7208,0,1,0,0,...,0,0,0,0,0,1,1,1,0,0
409,1301,0,3.0,1,1,13.7750,0,1,0,0,...,0,0,0,0,0,0,3,0,1,0
410,1302,0,18.0,0,0,7.7500,0,1,0,0,...,0,0,0,0,0,1,1,1,0,0
411,1303,0,37.0,1,0,90.0000,0,0,0,1,...,0,0,0,0,0,1,2,0,1,0
412,1304,0,28.0,0,0,7.7750,0,1,0,0,...,0,0,0,0,0,1,1,1,0,0
413,1305,1,26.0,0,0,8.0500,0,0,1,0,...,0,0,0,0,0,0,1,1,0,0
414,1306,0,39.0,0,0,108.9000,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
415,1307,1,38.5,0,0,7.2500,0,0,1,0,...,0,0,0,0,0,0,1,1,0,0
416,1308,1,26.0,0,0,8.0500,0,0,1,0,...,0,0,0,0,0,1,1,1,0,0
417,1309,1,6.0,1,1,22.3583,1,0,0,0,...,0,0,0,0,0,1,3,0,1,0

In [65]:
total.shape

(1309, 68)

经过特征工程后，获得共68个特征

这68个特征的范围处于不同区间，尝试进行标准化
（若使用其他标准化形式呢？）

In [66]:
features = list(total.columns)
features.remove('PassengerId')
total[features] = total[features].apply(lambda x: x/x.max(), axis=0)

In [67]:
total

,PassengerId,Sex,Age,SibSp,Parch,Fare,Title_Master,Title_Miss,Title_Mr,Title_Mrs,...,Ticket_STONO2,Ticket_STONOQ,Ticket_SWPP,Ticket_WC,Ticket_WEP,Ticket_XXX,FamilySize,Singleton,SmallFamily,LargeFamily
0,1,1.0,0.27500,0.125,0.000000,0.014151,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.181818,0.0,1.0,0.0
1,2,0.0,0.47500,0.125,0.000000,0.139136,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.181818,0.0,1.0,0.0
2,3,0.0,0.32500,0.000,0.000000,0.015469,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.090909,1.0,0.0,0.0
3,4,0.0,0.43750,0.125,0.000000,0.103644,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.181818,0.0,1.0,0.0
4,5,1.0,0.43750,0.000,0.000000,0.015713,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
5,6,1.0,0.35000,0.000,0.000000,0.016510,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
6,7,1.0,0.67500,0.000,0.000000,0.101229,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
7,8,1.0,0.02500,0.375,0.111111,0.041136,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.454545,0.0,0.0,1.0
8,9,0.0,0.33750,0.000,0.222222,0.021731,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.272727,0.0,1.0,0.0
9,10,0.0,0.17500,0.125,0.000000,0.058694,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.181818,0.0,1.0,0.0
10,11,0.0,0.05000,0.125,0.111111,0.032596,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.272727,0.0,1.0,0.0
11,12,0.0,0.72500,0.000,0.000000,0.051822,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
12,13,1.0,0.25000,0.000,0.000000,0.015713,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.090909,1.0,0.0,0.0
13,14,1.0,0.48750,0.125,0.555556,0.061045,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.636364,0.0,0.0,1.0
14,15,0.0,0.17500,0.000,0.000000,0.015330,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
15,16,0.0,0.68750,0.000,0.000000,0.031230,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
16,17,1.0,0.02500,0.500,0.111111,0.056848,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.545455,0.0,0.0,1.0
17,18,1.0,0.35000,0.000,0.000000,0.025374,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
18,19,0.0,0.38750,0.125,0.000000,0.035134,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.181818,0.0,1.0,0.0
19,20,0.0,0.35000,0.000,0.000000,0.014102,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
20,21,1.0,0.43750,0.000,0.000000,0.050749,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
21,22,1.0,0.42500,0.000,0.000000,0.025374,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
22,23,0.0,0.18750,0.000,0.000000,0.015672,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
23,24,1.0,0.35000,0.000,0.000000,0.069291,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
24,25,0.0,0.10000,0.375,0.111111,0.041136,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.454545,0.0,0.0,1.0
25,26,0.0,0.47500,0.125,0.555556,0.061264,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.636364,0.0,0.0,1.0
26,27,1.0,0.35000,0.000,0.000000,0.014102,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
27,28,1.0,0.23750,0.375,0.222222,0.513342,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.545455,0.0,0.0,1.0
28,29,0.0,0.35000,0.000,0.000000,0.015379,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
29,30,1.0,0.35000,0.000,0.000000,0.015412,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,1280,1.0,0.26250,0.000,0.000000,0.015127,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
389,1281,1.0,0.07500,0.375,0.111111,0.041136,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.454545,0.0,0.0,1.0
390,1282,1.0,0.28750,0.000,0.000000,0.182500,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
391,1283,0.0,0.63750,0.000,0.111111,0.076904,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.181818,0.0,1.0,0.0
392,1284,1.0,0.16250,0.000,0.222222,0.039525,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.272727,0.0,1.0,0.0
393,1285,1.0,0.58750,0.000,0.000000,0.020495,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.090909,1.0,0.0,0.0
394,1286,1.0,0.36250,0.375,0.111111,0.042990,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.454545,0.0,0.0,1.0
395,1287,0.0,0.22500,0.125,0.000000,0.117112,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.181818,0.0,1.0,0.0
396,1288,1.0,0.30000,0.000,0.000000,0.014151,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
397,1289,0.0,0.60000,0.125,0.111111,0.154588,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.272727,0.0,1.0,0.0
398,1290,1.0,0.27500,0.000,0.000000,0.015176,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
399,1291,1.0,0.38750,0.000,0.000000,0.015094,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
400,1292,0.0,0.37500,0.000,0.000000,0.321798,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
401,1293,1.0,0.47500,0.125,0.000000,0.040989,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.181818,0.0,1.0,0.0
402,1294,0.0,0.27500,0.000,0.111111,0.115941,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.181818,0.0,1.0,0.0
403,1295,1.0,0.21250,0.000,0.000000,0.091933,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
404,1296,1.0,0.53750,0.125,0.000000,0.054107,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.181818,0.0,1.0,0.0
405,1297,1.0,0.25000,0.000,0.000000,0.027058,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.090909,1.0,0.0,0.0
406,1298,1.0,0.28750,0.125,0.000000,0.020495,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.181818,0.0,1.0,0.0
407,1299,1.0,0.62500,0.125,0.111111,0.412821,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.272727,0.0,1.0,0.0
408,1300,0.0,0.22500,0.000,0.000000,0.015070,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
409,1301,0.0,0.03750,0.125,0.111111,0.026887,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.272727,0.0,1.0,0.0
410,1302,0.0,0.22500,0.000,0.000000,0.015127,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
411,1303,0.0,0.46250,0.125,0.000000,0.175668,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.181818,0.0,1.0,0.0
412,1304,0.0,0.35000,0.000,0.000000,0.015176,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
413,1305,1.0,0.32500,0.000,0.000000,0.015713,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.090909,1.0,0.0,0.0
414,1306,0.0,0.48750,0.000,0.000000,0.212559,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.090909,1.0,0.0,0.0
415,1307,1.0,0.48125,0.000,0.000000,0.014151,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.090909,1.0,0.0,0.0
416,1308,1.0,0.32500,0.000,0.000000,0.015713,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
417,1309,1.0,0.07500,0.125,0.111111,0.043640,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.272727,0.0,1.0,0.0

In [68]:
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectKBest
from sklearn.cross_validation import StratifiedKFold
from sklearn.grid_search import GridSearchCV
from sklearn.ensemble.gradient_boosting import GradientBoostingClassifier
from sklearn.cross_validation import cross_val_score

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)

为了评估模型，使用精度指标的5倍交叉验证。
为此，我们将定义一个小的评分函数。

In [69]:
def compute_score(clf, X, y,scoring='accuracy'):
    xval = cross_val_score(clf, X, y, cv = 5,scoring=scoring)
    return np.mean(xval)

In [74]:
def recover_train_test_target():
    global total
    
    train0 = pd.read_csv('train.csv')
    
    targets = train0.Survived
    train = total.iloc[0:890,:]
    test = total.iloc[891:,:]
    
    return train,test,targets

In [75]:
train,test,targets = recover_train_test_target()

In [76]:
train

,PassengerId,Sex,Age,SibSp,Parch,Fare,Title_Master,Title_Miss,Title_Mr,Title_Mrs,...,Ticket_STONO2,Ticket_STONOQ,Ticket_SWPP,Ticket_WC,Ticket_WEP,Ticket_XXX,FamilySize,Singleton,SmallFamily,LargeFamily
0,1,1.0,0.2750,0.125,0.000000,0.014151,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.181818,0.0,1.0,0.0
1,2,0.0,0.4750,0.125,0.000000,0.139136,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.181818,0.0,1.0,0.0
2,3,0.0,0.3250,0.000,0.000000,0.015469,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.090909,1.0,0.0,0.0
3,4,0.0,0.4375,0.125,0.000000,0.103644,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.181818,0.0,1.0,0.0
4,5,1.0,0.4375,0.000,0.000000,0.015713,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
5,6,1.0,0.3500,0.000,0.000000,0.016510,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
6,7,1.0,0.6750,0.000,0.000000,0.101229,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
7,8,1.0,0.0250,0.375,0.111111,0.041136,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.454545,0.0,0.0,1.0
8,9,0.0,0.3375,0.000,0.222222,0.021731,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.272727,0.0,1.0,0.0
9,10,0.0,0.1750,0.125,0.000000,0.058694,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.181818,0.0,1.0,0.0
10,11,0.0,0.0500,0.125,0.111111,0.032596,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.272727,0.0,1.0,0.0
11,12,0.0,0.7250,0.000,0.000000,0.051822,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
12,13,1.0,0.2500,0.000,0.000000,0.015713,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.090909,1.0,0.0,0.0
13,14,1.0,0.4875,0.125,0.555556,0.061045,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.636364,0.0,0.0,1.0
14,15,0.0,0.1750,0.000,0.000000,0.015330,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
15,16,0.0,0.6875,0.000,0.000000,0.031230,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
16,17,1.0,0.0250,0.500,0.111111,0.056848,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.545455,0.0,0.0,1.0
17,18,1.0,0.3500,0.000,0.000000,0.025374,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
18,19,0.0,0.3875,0.125,0.000000,0.035134,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.181818,0.0,1.0,0.0
19,20,0.0,0.3500,0.000,0.000000,0.014102,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
20,21,1.0,0.4375,0.000,0.000000,0.050749,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
21,22,1.0,0.4250,0.000,0.000000,0.025374,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
22,23,0.0,0.1875,0.000,0.000000,0.015672,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
23,24,1.0,0.3500,0.000,0.000000,0.069291,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
24,25,0.0,0.1000,0.375,0.111111,0.041136,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.454545,0.0,0.0,1.0
25,26,0.0,0.4750,0.125,0.555556,0.061264,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.636364,0.0,0.0,1.0
26,27,1.0,0.3500,0.000,0.000000,0.014102,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
27,28,1.0,0.2375,0.375,0.222222,0.513342,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.545455,0.0,0.0,1.0
28,29,0.0,0.3500,0.000,0.000000,0.015379,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
29,30,1.0,0.3500,0.000,0.000000,0.015412,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
860,861,1.0,0.5125,0.250,0.000000,0.027538,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.272727,0.0,1.0,0.0
861,862,1.0,0.2625,0.125,0.000000,0.022447,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.181818,0.0,1.0,0.0
862,863,0.0,0.6000,0.000,0.000000,0.050610,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
863,864,0.0,0.3500,1.000,0.222222,0.135753,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.0,0.0,1.0
864,865,1.0,0.3000,0.000,0.000000,0.025374,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
865,866,0.0,0.5250,0.000,0.000000,0.025374,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
866,867,0.0,0.3375,0.125,0.000000,0.027050,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.181818,0.0,1.0,0.0
867,868,1.0,0.3875,0.000,0.000000,0.098561,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.090909,1.0,0.0,0.0
868,869,1.0,0.3500,0.000,0.000000,0.018543,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
869,870,1.0,0.0500,0.125,0.111111,0.021731,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.272727,0.0,1.0,0.0
870,871,1.0,0.3250,0.000,0.000000,0.015412,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
871,872,0.0,0.5875,0.125,0.111111,0.102579,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.272727,0.0,1.0,0.0
872,873,1.0,0.4125,0.000,0.000000,0.009759,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
873,874,1.0,0.5875,0.000,0.000000,0.017567,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
874,875,0.0,0.3500,0.125,0.000000,0.046845,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.181818,0.0,1.0,0.0
875,876,0.0,0.1875,0.000,0.000000,0.014102,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
876,877,1.0,0.2500,0.000,0.000000,0.019218,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
877,878,1.0,0.2375,0.000,0.000000,0.015412,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
878,879,1.0,0.3500,0.000,0.000000,0.015412,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
879,880,0.0,0.7000,0.000,0.111111,0.162314,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.181818,0.0,1.0,0.0
880,881,0.0,0.3125,0.000,0.111111,0.050749,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.181818,0.0,1.0,0.0
881,882,1.0,0.4125,0.000,0.000000,0.015412,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
882,883,0.0,0.2750,0.000,0.000000,0.020527,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
883,884,1.0,0.3500,0.000,0.000000,0.020495,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.090909,1.0,0.0,0.0
884,885,1.0,0.3125,0.000,0.000000,0.013761,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.090909,1.0,0.0,0.0
885,886,0.0,0.4875,0.000,0.555556,0.056848,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.545455,0.0,0.0,1.0
886,887,1.0,0.3375,0.000,0.000000,0.025374,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
887,888,0.0,0.2375,0.000,0.000000,0.058556,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0
888,889,0.0,0.3500,0.125,0.222222,0.045771,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.363636,0.0,1.0,0.0
889,890,1.0,0.3250,0.000,0.000000,0.058556,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.090909,1.0,0.0,0.0

68个特征是相当大的。

当特征工程完成时，我们通过选择必不可少的特征来降低维度。以便减少数据之间的冗余、加快训练过程、减少过度拟合